---
title: "Resume"
---

### Education Experience

Sep 2021 - Jul 2025:

**Xi’an Jiaotong-Liverpool University**, Suzhou, China  

Bachelor of Science in Biomedical Statistics 

University Academic Achievement Award (Top 10% of students), Xi’an Jiaotong-Liverpool University (2022)

Sep 2025 till now:

**Columbia University**, New York, USA

Master of Science in Biostatistics

### Professional Expeirence

Jun 2023 - Aug 2023

**Summer Intern, Wuhan Huada Genomics Biotechnology Co., Ltd.** 
                    						          
•	Gained comprehensive knowledge of the operation and maintenance of the company’s business systems.  
•	Contributed to a codon optimization project in biomedicine, aiming to enhance RNA translation efficiency in vivo by optimizing RNA sequences to increase protein production.  
•	Developed and refined a codon optimization algorithm to evaluate the optimality of input RNA sequences. Incorporated a filtering mechanism to remove inefficient codon combinations and output improved sequences without changing the final synthesized protein.  
•	Conducted a literature review and built Python code to calculate the Codon Adaptation Index (CAI) for specified nucleotide sequences.  

Jun 2024 - Sep 2024

**Machine Learning Based Plasmodium Vivax Species Classification**

•	Performed data preprocessing using Python cv2, NumPy, TensorFlow and ImageDataGenerator package while ensuring data quality and improving analysis efficiency. Successfully solved the imbalanced classification data issue by cropping, rotating, and flipping photos to increase the amount of aberrant red blood cell photos.  
•	Optimized algorithms while training the model to enhance the model’s accuracy in identifying cell types by building a ResNet50 model. Ultimately achieved 95.73% accuracy.  
•	Collaboratively developed a project poster and an academic report to showcase our research outcomes.  
•	Worked with a team to design a website based on the trained model and enhance the visualization of the findings. The platform allows users to upload malaria-related images, process them with advanced models (include Faster R-CNN, ResNet50, DenseNet121 and VGG16), and receive diagnostic results in real-time.  
